version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SYSTEM_USER_UID=${SYSTEM_USER_UID:-1000}
        - SYSTEM_GROUP_GID=${SYSTEM_GROUP_GID:-1000}
    container_name: i-billboard-node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev

  redis:
    image: redis:7
    container_name: i-billboard-redis
    ports:
      - "6379:6379"
