version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i-billboard-node
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
